version: '3.8'
services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=8080
      - PREFIX=.
      - OWNER_NAME=natzsixn
      - OWNER_PHONE=6287748952040
      - STICKER_PACK_NAME=My Sticker Pack
      - STICKER_AUTHOR=Bot Author
      - STICKER_CATEGORIES=fun,whatsapp
      - MYSQL_ROOT_PASSWORD=password_yang_aman
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./sessions:/app/sessions
      - ./media:/app/media
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: whatsapp-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge